docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-validation:si-0.0.1 -f Dockerfile_validation .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing:si-0.0.3 -f Dockerfile_preprocessing .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-stitch:si-1.2.4 -f Dockerfile_stitch .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-registration:si-0.0.24 -f Dockerfile_registration .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-fuse:si-0.0.1 -f Dockerfile_fuse .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-dispatch:si-0.0.1 -f Dockerfile_dispatcher .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection:si-0.0.6 -f Dockerfile_cell_detection .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification:si-0.0.2 -f Dockerfile_cell_classification .
docker build -t ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification:si-1.0.1 -f Dockerfile_cell_quantification .
