# Start with the official TensorFlow runtime image
FROM tensorflow/tensorflow:2.11.0-gpu

# Set build arguments and environment variables to suppress prompts
ARG DEBIAN_FRONTEND=noninteractive
ENV PATH /opt/conda/bin:$PATH

# Install dependencies, Miniconda, and create the Conda environment
RUN apt-get update && apt-get install -y wget git && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    bash /miniconda.sh -b -p /opt/conda && \
    rm /miniconda.sh && \
    /opt/conda/bin/conda create -n cell_seg python=3.8 -y && \
    /opt/conda/bin/conda clean -afy && \
    apt-get remove --purge -y wget && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Activate the environment and install Python packages
RUN /opt/conda/bin/conda run -n cell_seg pip install -U --no-cache-dir \
    git+https://github.com/camilolaiton/cellfinder-core.git@block_seg \
    bokeh==2.4.2 \
    dask[distributed]==2022.11.1 \
    dask_memusage \
    argschema==3.0.4 \
    natsort==8.2.0 \
    astropy==5.2.1 \
    photutils==1.6.0 \
    imlib==0.1.3 \
    zarr==2.13.6 \
    aind-data-schema==1.0.0 \
    aind-ng-link==1.0.6 \
    psutil==5.9.8 \
    jupyter-server-proxy==3.2.2 \
    awscli

# Set Conda's default shell for the image
SHELL ["conda", "run", "-n", "cell_seg", "/bin/bash", "-c"]

# Set default command to bash
CMD ["bash"]