# Start with Miniconda base image
FROM continuumio/miniconda3:23.9.0-0

# Set noninteractive for automated installations
ARG DEBIAN_FRONTEND=noninteractive

# Install mamba for faster package handling, create environment, and install packages
RUN conda install -n base -c conda-forge mamba && \
    mamba create -n cell_seg python=3.8 -y && \
    mamba run -n cell_seg pip install -U --no-cache-dir \
        bokeh==2.4.2 \
        dask[distributed]==2022.11.1 \
        dask_memusage \
        argschema==3.0.4 \
        natsort==8.2.0 \
        astropy==5.2.1 \
        photutils==1.6.0 \
        imlib==0.1.3 \
        zarr==2.13.6 \
        aind-data-schema==1.0.0 \
        aind-ng-link==1.0.6 \
        jupyter-server-proxy==3.2.2 \
        git+https://github.com/camilolaiton/cellfinder-core.git@block_seg && \
    conda clean -afy && \
    rm -rf /root/.cache/pip

# Set Conda's default shell for subsequent commands
SHELL ["conda", "run", "-n", "cell_seg", "/bin/bash", "-c"]

# Set default command to bash
CMD ["bash"]
