FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

# Creating a new conda environment for argschema python bug
RUN conda create -n dispatcher python=3.8

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "dispatcher", "/bin/bash", "-c"]
RUN pip install -U --no-cache-dir \
    aind-codeocean-api==0.4.2 \
    python-dotenv==0.21.1 \
    aind-data-schema==1.0.0 \
    aind-ng-link==1.0.17 \
    python-dotenv==0.21.1 \
    smartsheet-dataframe==0.3.4

RUN conda install conda-forge::awscli
