# Base image with Miniconda
FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive
ARG MAVEN_VERSION=3.9.9

# Install necessary system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    libopenmpi-dev \
    software-properties-common \
    wget && \
    rm -rf /var/lib/apt/lists/*

# Clone TeraStitcher and build it
RUN git clone --depth=1 --branch fix/data_paths https://github.com/camilolaiton/TeraStitcher.git /home/TeraStitcher && \
    mkdir /home/build-terastitcher && \
    cd /home/build-terastitcher && \
    cmake -DWITH_UTILITY_MODULE_teraconverter=ON \
          -DWITH_UTILITY_MODULE_mdatagenerator=ON \
          -DWITH_UTILITY_MODULE_volumeconverter=ON \
          -DWITH_UTILITY_MODULE_mergedisplacements=ON \
          /home/TeraStitcher/src && \
    make -j$(nproc) && \
    make install && \
    rm -rf /home/TeraStitcher /home/build-terastitcher && \
    pip install --no-cache-dir --upgrade autopep8 && \
    autopep8 -i /home/TeraStitcher/src/utils/pyscripts/*.py

# Java setup with environment variables
RUN cd /home && \
    wget https://cdn.azul.com/zulu/bin/zulu8.62.0.19-ca-jdk8.0.332-linux_x64.tar.gz && \
    tar -xzf zulu8.62.0.19-ca-jdk8.0.332-linux_x64.tar.gz && \
    rm zulu8.62.0.19-ca-jdk8.0.332-linux_x64.tar.gz
ENV JAVA_HOME="/home/zulu8.62.0.19-ca-jdk8.0.332-linux_x64"
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/zulu8.62.0.19-ca-jdk8.0.332-linux_x64/jre/lib/amd64/server"
ENV PATH="$JAVA_HOME/bin:$PATH"

# Maven setup
RUN cd /home && \
    wget "https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" && \
    tar -xzf "apache-maven-$MAVEN_VERSION-bin.tar.gz" && \
    rm "apache-maven-$MAVEN_VERSION-bin.tar.gz"
ENV PATH="/home/apache-maven-$MAVEN_VERSION/bin:$PATH"

# MPI Configuration
RUN echo "localhost slots=70" > /home/hostfile

# Create Conda environment
RUN conda create -n smartspim_fusion python=3.8 -y && \
    conda clean -afy

# Set Conda's default shell for subsequent commands
SHELL ["conda", "run", "-n", "smartspim_fusion", "/bin/bash", "-c"]

# Install Python dependencies
RUN pip install -U --no-cache-dir \
    'tifffile < 2022.4.22' \
    xarray_multiscale==1.1.0 \
    argschema==3.0.4 \
    mpi4py \
    bokeh==2.4.2 \
    zarr==2.16.1 \
    pint==0.20.1 \
    aind-data-schema==1.0.0 \
    xmltodict==0.13.0 \
    natsort==8.2.0 \
    pims==0.6.1 \
    dask[distributed]==2022.11.1 \
    aind-ng-link==1.0.6 \
    ome-zarr==0.8.2 \
    psutil==5.9.5 \
    matplotlib==3.7.3 \
    imagecodecs[all]==2023.3.16

# Default command
CMD ["bash"]
