docker tag ghcr.io/allenneuraldynamics/aind-smartspim-validation:si-0.0.1 ghcr.io/allenneuraldynamics/aind-smartspim-validation:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing:si-0.0.3 ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-stitch:si-1.2.4 ghcr.io/allenneuraldynamics/aind-smartspim-stitch:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-registration:si-0.0.24 ghcr.io/allenneuraldynamics/aind-smartspim-registration:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-fuse:si-0.0.1 ghcr.io/allenneuraldynamics/aind-smartspim-fuse:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-dispatch:si-0.0.1 ghcr.io/allenneuraldynamics/aind-smartspim-dispatch:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection:si-0.0.6 ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification:si-0.0.2 ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification:si-1.0.1 ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification:latest

docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-validation
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-stitch
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-registration
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-fuse
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-dispatch
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification
