docker tag ghcr.io/allenneuraldynamics/aind-smartspim-flatfield-estimation:si-0.0.1 ghcr.io/allenneuraldynamics/aind-smartspim-flatfield-estimation:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing:si-0.0.4 ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-stitch:si-1.2.5 ghcr.io/allenneuraldynamics/aind-smartspim-stitch:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-registration:si-0.0.27 ghcr.io/allenneuraldynamics/aind-smartspim-registration:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-fuse:si-0.0.2 ghcr.io/allenneuraldynamics/aind-smartspim-fuse:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-dispatch:si-0.0.1 ghcr.io/allenneuraldynamics/aind-smartspim-dispatch:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection:si-0.0.7 ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification:si-0.0.3 ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification:latest
docker tag ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification:si-1.5.1 ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification:latest

docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-flatfield-estimation
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-preprocessing
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-stitch
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-registration
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-fuse
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-dispatch
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-cell-detection
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-cell-classification
docker push --all-tags ghcr.io/allenneuraldynamics/aind-smartspim-cell-quantification
